cc_test(
    name = "hello_pcl",
    srcs = ["hello_pcl.cpp"],
    deps = [
        "@pcl",
    ],
)

cc_test(
    name = "hello_loam",
    srcs = ["hello_loam.cpp"],
    deps = [
        "//loam",
    ],
)
