cc_test(
    name = "hello_pcl",
    srcs = ["hello_pcl.cpp"],
    deps = [
        "@pcl",
    ],
)

cc_binary(
    name = "loam_odom",
    srcs = ["loam_odom.cpp"],
    deps = [
        "//loam",
    ],
)
